server:
  port: 10010
spring:
  application:
    name: ly-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 添加路由前置
  routes:
    item-service: /item/**  # 商品微服务的映射路径
    search-service: /search/**  # 搜索微服务
    user-service: /user/**  # 用户微服务
    auth-service: /auth/**  # 授权中心微服务
    cart-service: /cart/**  # 购物车微服务
    order-service: /order/**  # 订单微服务
    upload-service: # 图片上传微服务
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  add-host-header: true # 携带请求本身的head头信息
  sensitive-headers:  # 配置禁用使用的头信息，这里设置为null，否则set-cookie无效
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 熔断超时时长：5000ms
ribbon:
  ConnectTimeout: 1000 # ribbon连接超时时长
  ReadTimeout: 3500 # ribbon读取超时时长
  MaxAutoRetries: 0 # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数
leyou:
  jwt:
    pubKeyPath: E:\prictice6_JavaEE\projects\leyou\data\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths: # 网关白名单，放行列表
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item

