server:
  port: 8089
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.43.111
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
leyou:
  jwt:
    pubKeyPath: E:\prictice6_JavaEE\projects\leyou\data\rsa.pub # 公钥地址
    cookieName: LY_TOKEN